//! Embedded math assets generated by build script.
//! This file is auto-generated - DO NOT EDIT MANUALLY.
//!
//! When the build script runs, it will replace this stub with actual
//! embedded formula data.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Metadata for a rendered formula
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FormulaMetadata {
    /// The original formula text
    pub formula: String,
    /// Whether this is display math (true) or inline math (false)
    pub is_display: bool,
    /// When this formula was last rendered (ISO 8601)
    pub rendered_at: String,
    /// Size of the SVG file in bytes
    pub svg_size: usize,
    /// The hash used as filename
    pub hash: String,
    /// Whether this is a placeholder SVG (true) or actual Typst rendering (false)
    pub is_placeholder: bool,
    /// Whether this SVG has been processed for theme adaptation (true)
    #[serde(default = "default_theme_processed")]
    pub theme_processed: bool,
}

fn default_theme_processed() -> bool {
    true
}

/// Manifest tracking all rendered formulas
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MathManifest {
    /// Map from formula hash to metadata
    pub formulas: HashMap<String, FormulaMetadata>,
    /// When this manifest was last updated
    pub updated_at: String,
}

impl MathManifest {
    /// Find the hash for a formula
    pub fn find_hash(&self, formula: &str, is_display: bool) -> Option<&str> {
        self.formulas
            .iter()
            .find(|(_, metadata)| metadata.formula == formula && metadata.is_display == is_display)
            .map(|(hash, _)| hash.as_str())
    }

    /// Get all hashes in the manifest
    pub fn all_hashes(&self) -> Vec<&str> {
        self.formulas.keys().map(|k| k.as_str()).collect()
    }

    /// Get metadata for a hash
    pub fn get_metadata(&self, hash: &str) -> Option<&FormulaMetadata> {
        self.formulas.get(hash)
    }
}

/// Load the embedded manifest
/// Returns an empty manifest if no formulas have been generated yet
pub fn load_manifest() -> MathManifest {
    MathManifest {
        formulas: HashMap::new(),
        updated_at: "1970-01-01T00:00:00Z".to_string(),
    }
}

/// Get SVG bytes for a hash
/// Returns None if the hash doesn't exist or no SVGs have been generated yet
pub fn get_svg_bytes(_hash: &str) -> Option<&'static [u8]> {
    None
}
